---
title: "NY Reading Report Card - 2021"
---
```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)
library(kableExtra)
library(flexdashboard)
library(WDI)
library(tidyverse)
library(plotly)
library(crosstalk)
library(ggthemes)
library(dplyr)

##########################################
######  CHANGE INFO FOR CHART HERE - Making ONE HTML Page per Year ######
YEAR <-  "2021"                         # School Year Ending Year.  No 2020 data (due to COVID)

##########################################

############################################################
## Import Data
data_read <- read.csv("SOURCEDATA_ALLDistrictsGrades.csv")  #[,c(1,3,4,5,6,7,9,10,11,12,13,14,24)]
shared_data <- data_read

#################### Changeable Data Stuff   ##########
# Keep 3rd Grade ELA data 
shared_data<-shared_data[( shared_data$ITEM_DESC == "Grade 3 ELA"),]

# Keep Select Subgroup (selection made at top of program)
shared_data<-shared_data[( shared_data$SUBGROUP_CODE == 15),] #15=econ disadvantaged

# Keep Select Counties (selection made at top of program)
# shared_data<- shared_data[shared_data$COUNTY_DESC %in% COUNTIES,]  # Keeping all counties

# Keep Selected year (selection made at top of program) (this report is for 1 year report card)
shared_data<-shared_data[(shared_data$SY_END_DATE == YEAR),]

# Only Keep Districts that tested 10 or more students in the chosen cohort:
shared_data<-shared_data[(shared_data$TOTAL_TESTED > 9),]

#######################################################################
# Get rid of NA Prof rates, and sort by Prof rate
shared_data <- shared_data %>% 
  filter(!is.na(L3.L4_PCT)) %>% 
  dplyr::arrange(L3.L4_PCT) 

# Create NotProf column (=100 - %Proficient)
notprof <- function(x, na.rm = TRUE) {  
( 100 - x ) }
shared_data$NotProf <- sapply(shared_data$L3.L4_PCT, notprof)

# Sort it
shared_data <- shared_data[order(shared_data$COUNTY_DESC, shared_data$L3.L4_PCT),]

# Save total number of districts
NumDistricts <- nrow(shared_data)
```
#### School Year, Ending: `r YEAR`  

```{r plotly-crosstalk, echo = FALSE, message = FALSE, warning = FALSE}

##########
## Config Plot ##

# Define Font for Title Bar
t1 <- list(
  family = "Arial",
  color = "black",
  size = 14
)


# For vertical line on plot, at 95%, the amount of kids capable of reading
vline <- function(x = 0) {
  list(
    type = "line", 
    y0 = 0, 
    y1 = 1, 
    yref = "paper",
    x0 = x, 
    x1 = x, 
    line = list(color = "black", dash = "dash", annotation_text="95%")  #could use 'dotted instead of dash
  )
}
# For Text by verticle line
m <- shared_data[which.max(shared_data$L3.L4_PCT), ]
a <- list(
  x = 95,
  y = m$NAME,
  text = "95%",
  xref = "x",
  yref = "y",
  showarrow = TRUE,
  arrowhead = 0,
  ax = 20,
  ay = -20
)

# Make Interactive
# sd <- highlight_key(shared_data)  #adding, ~NAME stops the checkbox filter from working
sd <- SharedData$new(shared_data)

# Make Interactive Filters
user_filts <- filter_select("filt_COUNTY", "Select County:", sd, ~COUNTY_DESC, multiple = FALSE) #Variable is 'group by'

# Make Plot, removed - height = NumDistricts*22
fig <- plot_ly(sd, x = ~L3.L4_PCT, y = ~NAME, type = 'bar', orientation = 'h', name = 'Proficienct', width = 950)  %>%  
      add_trace(x = ~NotProf, name = 'Not Proficient') %>% 
  
      config(displayModeBar = F) %>%  # Get rid of Plotly Bar
  
      layout(xaxis = list(title = '% Proficient'), 
             yaxis = list(title = '', 
                          categoryorder = "array",
                          categoryarray = ~COUNTY_DESC),  #change $Name to L3.L4 to sort by prof
             barmode = 'stack'  
             )

bscols(widths = 12, user_filts, fig)  # total page width=12

# To dos
# To fix the list to include all:
#  https://stackoverflow.com/questions/40024029/plotly-updating-data-with-dropdown-selection/66385494#66385494
# or To: try with 'filter_by' again 

```

<!-- ```{js} -->
<!-- <!-- Sets Filter Default -->
<!-- function filter_default() { -->
<!--     document.getElementById("filt_COUNTY").getElementsByClassName("selectized")[0].selectize.setValue("NASSAU", false); -->
<!-- } -->
<!-- $(document).ready(filter_default);  -->

<!-- <!-- names.sort(); --> -->
<!-- <!-- document.getElementById("demo").innerHTML = names; --> -->
<!-- <!-- window.onload = filter_default; --> -->

<!-- ``` -->
# References, Notes:  
* Data from: [NY State Report Card](https://data.nysed.gov/downloads.php)  
* Students Included: 3rd graders, "Economically Disadvantaged" - [Why?](https://www.careads.org/why-these-students) 
* Districts Included: Those which tested => 10 Students
* Total Districts: `r NumDistricts`  
  